### ISSUE TITLE
remove .tg .tg-0pky from css file

### ISSUE THREAD

**Issue by filkovsp** [robloxcoolabc123/Web-Calculator#3]
this style isn't in use
```css
.tg .tg-0pky{
    border-color:inherit;
    text-align:center;
    vertical-align:center;
    padding:2px;
}
```
