### ISSUE TITLE
add margins for table grid in css

### ISSUE THREAD

**Issue by filkovsp** [robloxcoolabc123/Web-Calculator#6]
in style.css for class `tg` (table grid) add `margin-top = 15vh;` property.
this is means 15% of view-height (height of the visible screen area on the device)
also add `margin-top` and `margin-left` both equal `auto` to align table to the centre of the screen:
```css
.tg  {
    margin-top: 15vh;
    margin-left:auto; 
    margin-right:auto;
....
}
```
